FROM python:3.11

WORKDIR /app

RUN pip install --upgrade pip

COPY . .
RUN pip install -e catanatron_core
RUN pip install -e catanatron_server
RUN pip install -e catanatron_gym
RUN pip install -e catanatron_experimental
RUN pip install sb3-contrib stable-baselines3 torch --extra-index-url https://download.pytorch.org/whl/cpu

EXPOSE 5000

ENV FLASK_DEBUG=1
ENV FLASK_APP=catanatron_server/catanatron_server
ENV FLASK_RUN_HOST=0.0.0.0
ENV PYTHONPATH=/app/catanatron_server:/app/catanatron_core:/app/catanatron_experimental:/app/catanatron_gym

CMD python -m catanatron_server.run
